id: b4abd09c-3a80-4dc4-9bff-223d951c960c
type: web-application
interactions:
- targetId: 8f580963-407c-4e98-a3dc-34dcf8a797cb
  type: gateway
  level: container
annotations:
- namespace: c4modeler
  name: position
  value:
    ecdb3be2-4cdc-49a6-9d22-68725902a9a6:
      x: 435.5896302250804
      y: 124.2154379596281
- namespace: c4modeler
  name: boundary
  value:
    x: 140
    y: 375.5
    width: 280
    height: 751
prefix: app
author: CodeArchitects
target: angular@19
architecture: single-page-application
strict: false
name: NewWebApplication
description: Description for NewWebApplication
children:
- id: 461cfc2a-fe54-48f3-bf7a-eefa129c13f8
  type: application
- id: 10dd77fd-8f74-4404-bf9b-53fe76b10fea
  type: domain
- id: 0fd19d05-82da-4b12-a6f9-eac92de293df
  type: scenario
